/**
 * What the server knows about one incident.
 *
 * The page reads this when it comes back: after a reload, after a laptop woke
 * up, after a phone discarded the tab mid-escalation. Everything it returns was
 * written by the webhook receiver from an authenticated read of the CALL-E API,
 * never from a delivery body.
 *
 * The incident id is generated by the client and is not a secret, so this
 * returns only what the operator of that incident already had on screen: call
 * ids, the decision each call produced, and the transcript of a call this
 * deployment placed. It never returns the rota, a phone number, or the key.
 */

import { getIncidentStore } from '../../_lib/incidentStore.js';

export default function handler(req, res) {
  res.setHeader('content-type', 'application/json');
  res.setHeader('cache-control', 'no-store');

  if (req.method !== 'GET') {
    res.status(405).json({ error: { code: 'method_not_allowed', message: 'Read with GET.', details: {} } });
    return;
  }

  const id = req.query?.id || new URL(req.url, 'http://reader.local').pathname.split('/').pop();
  const store = getIncidentStore(process.env);
  const incident = store.get(id);

  res.status(200).json({
    incidentId: id,
    found: Boolean(incident),
    // Said out loud rather than implied, because "no outcome recorded" means
    // something different depending on whether this store can remember at all.
    durability: store.describeDurability(),
    persistent: store.isPersistent,
    calls: incident?.calls || []
  });
}
